name: gnome-taquin
adopt-info: gnome-taquin
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  gnome-taquin:
    interface: dbus
    bus: session
    name: org.gnome.Taquin

layout:
 /usr/share/gnome-taquin:
   symlink: $SNAP/usr/share/gnome-taquin

apps:
  gnome-taquin:
    extensions: [ gnome ]
    command: usr/bin/gnome-taquin
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.Taquin.desktop

parts:
  gnome-taquin:
    source: https://gitlab.gnome.org/GNOME/gnome-taquin.git
    source-type: git
    source-tag: '3.38.1'
    parse-info: [usr/share/metainfo/org.gnome.Taquin.appdata.xml]
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/patch1.diff
    override-build: |
      sed -i.bak -e 's|=gnome-taquin$|=${SNAP}/meta/gui/org.gnome.Taquin.svg|g' $CRAFT_PART_SRC/data/org.gnome.Taquin.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/org.gnome.Taquin.svg $CRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Taquin.desktop $CRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
      - --prefix=/usr
